site_name: Image formatter plugin for MkDocs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Plugin: plugin.md
  - Lexer: lexer.md
  - Parser: image_properties_tag_replacer.md
