site_name: Test with cats

dev_addr: 127.0.0.1:8002

theme:
  name: "material"

markdown_extensions:
  - attr_list

plugins:
  - mkdocstrings
  - image-formatter:
      image_size:
        small:
          height: 250px
          width: 250px
        big:
          height: 500px
          width: 500px

nav:
  - Home: index.md
